### ISSUE TITLE
failed to compile fastswap driver

### ISSUE THREAD

**Issue by KitLing** [clusterfarmem/fastswap#1]
There are some problems when I try to compile the fastswap driver.
The detail is as follow:

environmont:
ubuntu16.04（4.11.0-14-generic）
MLNX_OFED_LINUX-4.3-1.0.1.0-ubuntu16.04-x86_64

hardware
ConnectX-5

I do just as the readme.md said, use the script to install and run successfully. But when I try to compile the fastswap driver，An error was reported as shown in the figure in the link.After searching, I found that the variable was defined in Kernel.patch.But when I patched the file, It didn't work.
Put the image in the following link(Album name: error in fastswap):

Hoping for your help,
thanks.

**Comment by amaro** [comment]
In order to compile the fastswap driver you need to boot the patched kernel. Did you do that?
If so, can you paste the error you get here? I can't access your link.

**Comment by KitLing** [comment]
> In order to compile the fastswap driver you need to boot the patched kernel. Did you do that?
> If so, can you paste the error you get here? I can't access your link.

When I try to compile the FastSwap driver,An error occurred as shown in the figure below,And I have been in the fastSwap kernel:

![1](https://user-images.githubusercontent.com/71744256/99869079-40e1dc80-2c03-11eb-847d-546d1331d4ef.png)
![4](https://user-images.githubusercontent.com/71744256/99869088-5951f700-2c03-11eb-803f-3f89a4fada96.jpg)

After searching,I found these fields in Kerne.patch,But when I patched the file in linux-4.11,It didn't work.At this time,I repatched it and got an error.the error is as follows:
![2](https://user-images.githubusercontent.com/71744256/99869129-87373b80-2c03-11eb-9cb4-e3882387b9dd.png)
![3](https://user-images.githubusercontent.com/71744256/99869144-9c13cf00-2c03-11eb-8812-f1e6e487d9fe.jpg)

I'm not sure if the patch kernel booted successfully,Or something else problems.
Hoping for your help.

**Comment by amaro** [comment]
You didn't boot the fastswap *kernel* when you tried to compile the fastswap driver; e.g.:

    make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-fastswap  
    cd ..   
    sudo dpkg -i *.deb. 
    reboot here and make sure `uname -a` shows the -fastswap kernel booted

If you are having issues applying the patch, then make sure you got the exact kernel version we require; i.e.:

    wget https://github.com/torvalds/linux/archive/a351e9b9fc24e982ec2f0e76379a49826036da12.zip  

More generally, it sounds like you missed/skipped steps in the instructions. If you follow them correctly you should be able to get it working.
