### ISSUE TITLE
Issue arising when using fastswap rdma backend

### ISSUE THREAD

**Issue by jiaweixiao** [clusterfarmem/fastswap#3]
I am using two nodes, one for client and the other for memory server. 
The HW/SW infomation: 
* NIC: ConnextX-5 
* NIC driver: MLNX_OFED_LINUX-4.3-1.0.1.0-ubuntu18.04-x86_64
* OS: Ubuntu 18.04.5 server  

After finishing the instructions in README.md, I did a functional test including the following steps:
1. [**Passed**] Test the NIC with its ipv4 address using `ib_read_bw` in two directions;
2. [**Passed**] Test the fastswap DRAM backend with the _cgroup-v1_ `memory.limit_in_bytes` parameter and a simple streaming program on client;
3. [**Passed**] Start the `rmserver` and install the fastswap RDMA module on client;
The output of `dmesg`:
```
[  189.193283] fastswap_rdma: ctrl is ready for reqs
[  189.211845] fastswap: sswap_init end
[  189.211848] fastswap: sswap module loaded
```
4. [**Failed**]Test the fastswap RDMA backend with _cgroup-v1_ and a simple streaming program on client;
The output of `dmesg`:
```
[ 9370.869034] BUG: unable to handle kernel NULL pointer dereference at           (null)
[ 9370.869945] IP: sswap_rdma_write+0x6d/0x380 [fastswap_rdma]
[ 9370.870699] PGD 0

[ 9370.871969] Oops: 0000 [#6] SMP
[ 9370.872403] Modules linked in: fastswap(OE) fastswap_rdma(OE) rdma_ucm(OE) ib_ucm(OE) ib_iser(OE) rdma_cm(OE) iw_cm(OE) ib_ipoib(OE) ib_cm(OE) ib_uverbs(OE) ib_umad(OE) mlx5_fpga_tools(OE) mlx5_ib(OE) mlx5_core(OE) mlxfw(OE) mlx4_en(OE) mlx4_ib(OE) ib_core(OE) mlx4_core(OE) devlink mlx_compat(OE) intel_rapl skx_edac edac_core x86_pkg_temp_thermal coretemp kvm_intel kvm irqbypass ipmi_ssif mei_me intel_rapl_perf input_leds joydev shpchp mei lpc_ich ioatdma dca ipmi_si ipmi_devintf ipmi_msghandler nfit mac_hid acpi_power_meter sch_fq_codel configfs iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi knem(OE) bonding ip_tables x_tables autofs4 btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear crct10dif_pclmul ast crc32_pclmul
[ 9370.875888]  i2c_algo_bit ghash_clmulni_intel ttm hid_generic pcbc drm_kms_helper aesni_intel i40e syscopyarea aes_x86_64 sysfillrect crypto_simd sysimgblt ptp glue_helper uas nvme fb_sys_fops usbhid ahci cryptd nvme_core megaraid_sas hid usb_storage drm pps_core libahci wmi [last unloaded: devlink]
[ 9370.877596] CPU: 27 PID: 10015 Comm: test Tainted: G      D    OE   4.11.0-fastswap #3
[ 9370.878193] Hardware name: XXX, BIOS 0THSY017 01/03/2019
[ 9370.878794] task: ffff8a47e083bb00 task.stack: ffff9dc0b25d8000
[ 9370.879406] RIP: 0010:sswap_rdma_write+0x6d/0x380 [fastswap_rdma]
[ 9370.880011] RSP: 0000:ffff9dc0b25db728 EFLAGS: 00010282
[ 9370.880618] RAX: 0000000000000000 RBX: ffffffffc06d8000 RCX: 00000000000001d9
[ 9370.881237] RDX: ffff8a67f2511880 RSI: 0000000015c00000 RDI: ffffe388009529c0
[ 9370.881858] RBP: ffff9dc0b25db7c0 R08: ffff9dc0b154d2f8 R09: 0000000008000000
[ 9370.882486] R10: 0000000000015c00 R11: ffff8a77f1442650 R12: ffff8a67f26b86c8
[ 9370.883096] R13: ffff8a67f26b86d8 R14: 0000000000000001 R15: ffff8a77f1442600
[ 9370.883712] FS:  00007fce99bdc540(0000) GS:ffff8a57febc0000(0000) knlGS:0000000000000000
[ 9370.884337] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 9370.884964] CR2: 0000000000000000 CR3: 0000002034ed6000 CR4: 00000000007406e0
[ 9370.885597] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 9370.886230] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[ 9370.886862] PKRU: 55555554
[ 9370.887490] Call Trace:
[ 9370.888123]  ? try_to_unmap_one+0xa4/0x670
[ 9370.888758]  sswap_store+0x15/0x2c [fastswap]
[ 9370.889394]  __frontswap_store+0x6d/0xd0
[ 9370.890029]  swap_writepage+0x49/0x90
[ 9370.890670]  pageout.isra.47+0xf2/0x2d0
[ 9370.891303]  shrink_page_list+0x87c/0xa10
[ 9370.891950]  shrink_inactive_list+0x1da/0x4e0
[ 9370.892577]  ? destroy_inode+0x3b/0x60
[ 9370.893201]  shrink_node_memcg+0x402/0x7f0
[ 9370.893822]  shrink_node+0xdb/0x300
[ 9370.894440]  ? shrink_node+0xdb/0x300
[ 9370.895042]  do_try_to_free_pages+0xd7/0x2e0
[ 9370.895630]  try_to_free_mem_cgroup_pages+0xdb/0x1b0
[ 9370.896209]  try_charge+0x148/0x720
[ 9370.896782]  mem_cgroup_try_charge+0x83/0x160
[ 9370.897358]  __handle_mm_fault+0x824/0x10d0
[ 9370.897922]  ? tty_ldisc_deref+0x16/0x20
[ 9370.898482]  ? tty_write+0x1fd/0x320
[ 9370.899035]  handle_mm_fault+0xb3/0x250
[ 9370.899595]  __do_page_fault+0x23f/0x4c0
[ 9370.900156]  do_page_fault+0x22/0x30
[ 9370.900699]  page_fault+0x28/0x30
[ 9370.901222] RIP: 0033:0x7fce99b77ad1
[ 9370.901725] RSP: 002b:00007ffc817dc288 EFLAGS: 00010206
[ 9370.902236] RAX: 0000000000000018 RBX: 0000558253e38920 RCX: 00000000000af010
[ 9370.902724] RDX: 00007fce980d0010 RSI: 0000000000000018 RDI: 00007fce98121000
[ 9370.903195] RBP: 00007ffc817de2b0 R08: 0000000000000000 R09: 0000000000000014
[ 9370.903651] R10: 0000558253e389dd R11: 0000000000000246 R12: 0000558253e386d0
[ 9370.904094] R13: 00007ffc817de3a0 R14: 0000000000000000 R15: 0000000000000000
[ 9370.904515] Code: 48 89 b5 68 ff ff ff 48 89 bd 70 ff ff ff 8d 04 48 48 8d 0c 80 48 8d 0c 48 48 8b 42 08 4c 8d 24 c8 49 8b 44 24 18 4d 8d 6c 24 10 <48> 8b 00 4c 8b 38 48 c7 45 88 00 00 00 00 48 c7 45 90 00 00 00
[ 9370.905395] RIP: sswap_rdma_write+0x6d/0x380 [fastswap_rdma] RSP: ffff9dc0b25db728
[ 9370.905825] CR2: 0000000000000000
[ 9370.908408] ---[ end trace d901789a7c62158f ]---
```
If you could solve the problem, I would really appreciate it. Thank you.

**Comment by stmatengss** [comment]
> I am using two nodes, one for client and the other for memory server. The HW/SW infomation:
> 
> * NIC: ConnextX-5
> * NIC driver: MLNX_OFED_LINUX-4.3-1.0.1.0-ubuntu18.04-x86_64
> * OS: Ubuntu 18.04.5 server
> 
> After finishing the instructions in README.md, I did a functional test including the following steps:
> 
> 1. [**Passed**] Test the NIC with its ipv4 address using `ib_read_bw` in two directions;
> 2. [**Passed**] Test the fastswap DRAM backend with the _cgroup-v1_ `memory.limit_in_bytes` parameter and a simple streaming program on client;
> 3. [**Passed**] Start the `rmserver` and install the fastswap RDMA module on client;
>    The output of `dmesg`:
> 
> ```
> [  189.193283] fastswap_rdma: ctrl is ready for reqs
> [  189.211845] fastswap: sswap_init end
> [  189.211848] fastswap: sswap module loaded
> ```
> 
> 4. [**Failed**]Test the fastswap RDMA backend with _cgroup-v1_ and a simple streaming program on client;
>    The output of `dmesg`:
> 
> ```
> [ 9370.869034] BUG: unable to handle kernel NULL pointer dereference at           (null)
> [ 9370.869945] IP: sswap_rdma_write+0x6d/0x380 [fastswap_rdma]
> [ 9370.870699] PGD 0
> 
> [ 9370.871969] Oops: 0000 [#6] SMP
> [ 9370.872403] Modules linked in: fastswap(OE) fastswap_rdma(OE) rdma_ucm(OE) ib_ucm(OE) ib_iser(OE) rdma_cm(OE) iw_cm(OE) ib_ipoib(OE) ib_cm(OE) ib_uverbs(OE) ib_umad(OE) mlx5_fpga_tools(OE) mlx5_ib(OE) mlx5_core(OE) mlxfw(OE) mlx4_en(OE) mlx4_ib(OE) ib_core(OE) mlx4_core(OE) devlink mlx_compat(OE) intel_rapl skx_edac edac_core x86_pkg_temp_thermal coretemp kvm_intel kvm irqbypass ipmi_ssif mei_me intel_rapl_perf input_leds joydev shpchp mei lpc_ich ioatdma dca ipmi_si ipmi_devintf ipmi_msghandler nfit mac_hid acpi_power_meter sch_fq_codel configfs iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi knem(OE) bonding ip_tables x_tables autofs4 btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear crct10dif_pclmul ast crc32_pclmul
> [ 9370.875888]  i2c_algo_bit ghash_clmulni_intel ttm hid_generic pcbc drm_kms_helper aesni_intel i40e syscopyarea aes_x86_64 sysfillrect crypto_simd sysimgblt ptp glue_helper uas nvme fb_sys_fops usbhid ahci cryptd nvme_core megaraid_sas hid usb_storage drm pps_core libahci wmi [last unloaded: devlink]
> [ 9370.877596] CPU: 27 PID: 10015 Comm: test Tainted: G      D    OE   4.11.0-fastswap #3
> [ 9370.878193] Hardware name: XXX, BIOS 0THSY017 01/03/2019
> [ 9370.878794] task: ffff8a47e083bb00 task.stack: ffff9dc0b25d8000
> [ 9370.879406] RIP: 0010:sswap_rdma_write+0x6d/0x380 [fastswap_rdma]
> [ 9370.880011] RSP: 0000:ffff9dc0b25db728 EFLAGS: 00010282
> [ 9370.880618] RAX: 0000000000000000 RBX: ffffffffc06d8000 RCX: 00000000000001d9
> [ 9370.881237] RDX: ffff8a67f2511880 RSI: 0000000015c00000 RDI: ffffe388009529c0
> [ 9370.881858] RBP: ffff9dc0b25db7c0 R08: ffff9dc0b154d2f8 R09: 0000000008000000
> [ 9370.882486] R10: 0000000000015c00 R11: ffff8a77f1442650 R12: ffff8a67f26b86c8
> [ 9370.883096] R13: ffff8a67f26b86d8 R14: 0000000000000001 R15: ffff8a77f1442600
> [ 9370.883712] FS:  00007fce99bdc540(0000) GS:ffff8a57febc0000(0000) knlGS:0000000000000000
> [ 9370.884337] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
> [ 9370.884964] CR2: 0000000000000000 CR3: 0000002034ed6000 CR4: 00000000007406e0
> [ 9370.885597] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
> [ 9370.886230] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
> [ 9370.886862] PKRU: 55555554
> [ 9370.887490] Call Trace:
> [ 9370.888123]  ? try_to_unmap_one+0xa4/0x670
> [ 9370.888758]  sswap_store+0x15/0x2c [fastswap]
> [ 9370.889394]  __frontswap_store+0x6d/0xd0
> [ 9370.890029]  swap_writepage+0x49/0x90
> [ 9370.890670]  pageout.isra.47+0xf2/0x2d0
> [ 9370.891303]  shrink_page_list+0x87c/0xa10
> [ 9370.891950]  shrink_inactive_list+0x1da/0x4e0
> [ 9370.892577]  ? destroy_inode+0x3b/0x60
> [ 9370.893201]  shrink_node_memcg+0x402/0x7f0
> [ 9370.893822]  shrink_node+0xdb/0x300
> [ 9370.894440]  ? shrink_node+0xdb/0x300
> [ 9370.895042]  do_try_to_free_pages+0xd7/0x2e0
> [ 9370.895630]  try_to_free_mem_cgroup_pages+0xdb/0x1b0
> [ 9370.896209]  try_charge+0x148/0x720
> [ 9370.896782]  mem_cgroup_try_charge+0x83/0x160
> [ 9370.897358]  __handle_mm_fault+0x824/0x10d0
> [ 9370.897922]  ? tty_ldisc_deref+0x16/0x20
> [ 9370.898482]  ? tty_write+0x1fd/0x320
> [ 9370.899035]  handle_mm_fault+0xb3/0x250
> [ 9370.899595]  __do_page_fault+0x23f/0x4c0
> [ 9370.900156]  do_page_fault+0x22/0x30
> [ 9370.900699]  page_fault+0x28/0x30
> [ 9370.901222] RIP: 0033:0x7fce99b77ad1
> [ 9370.901725] RSP: 002b:00007ffc817dc288 EFLAGS: 00010206
> [ 9370.902236] RAX: 0000000000000018 RBX: 0000558253e38920 RCX: 00000000000af010
> [ 9370.902724] RDX: 00007fce980d0010 RSI: 0000000000000018 RDI: 00007fce98121000
> [ 9370.903195] RBP: 00007ffc817de2b0 R08: 0000000000000000 R09: 0000000000000014
> [ 9370.903651] R10: 0000558253e389dd R11: 0000000000000246 R12: 0000558253e386d0
> [ 9370.904094] R13: 00007ffc817de3a0 R14: 0000000000000000 R15: 0000000000000000
> [ 9370.904515] Code: 48 89 b5 68 ff ff ff 48 89 bd 70 ff ff ff 8d 04 48 48 8d 0c 80 48 8d 0c 48 48 8b 42 08 4c 8d 24 c8 49 8b 44 24 18 4d 8d 6c 24 10 <48> 8b 00 4c 8b 38 48 c7 45 88 00 00 00 00 48 c7 45 90 00 00 00
> [ 9370.905395] RIP: sswap_rdma_write+0x6d/0x380 [fastswap_rdma] RSP: ffff9dc0b25db728
> [ 9370.905825] CR2: 0000000000000000
> [ 9370.908408] ---[ end trace d901789a7c62158f ]---
> ```
> 
> If you could solve the problem, I would really appreciate it. Thank you.

Hi Dude, I have the same issue. Just like this 

[ 7571.722037] BUG: unable to handle kernel NULL pointer dereference at           (null)
[ 7571.729886] IP: sswap_rdma_write+0x6d/0x380 [fastswap_rdma]
[ 7571.735471] PGD 3f63c83067
[ 7571.735472] PUD 3f625a2067
[ 7571.738271] PMD 0

Do u have any idea now?

Thank you~

**Comment by amaro** [comment]
@jiaweixiao Are you using cgroup-v1 or cgroup-v2? Your message says group-v1 but that's not supported.
Also, make sure you are pinning the stream program you mentioned to a given cpu; e.g., using taskset.
If you are still having issues can you include your dmesg logs when fastswap is connected, and the command line you are using to start your stream program?

@stmatengss it's hard to say without you providing more information. please provide logs so I can help.

**Comment by jiaweixiao** [comment]
Thank you, I will try with cgroup-v2.
